# Add path variables
#export PATH="$HOME/.rvm/bin:$PATH" # Add RVM to PATH for scripting
#export PATH="$HOME/.bin:$PATH"
export PATH="/usr/local/bin:$PATH"

# From ut
source /usr/local/share/antigen/antigen.zsh
#source ~/.antigen.zsh
antigen use oh-my-zsh

antigen bundle git
antigen bundle zsh-users/zsh-syntax-highlighting

antigen theme fishy
antigen apply

# Add anaconda to path
export PATH=~/miniconda3/bin:$PATH

# alias for a-vim-story
alias avimstory="$HOME/coding_practice/a-vim-story/build/bin/a-vim-story"

# Java home
export JAVA_HOME=$(/usr/libexec/java_home)
